### ISSUE TITLE
Upgrade Gatsby version

### ISSUE THREAD

**Issue by arafatamim** [Js-Brecht/gatsby-plugin-pnpm#11]
FYI, It still works on local builds, but Netlify refuses to build site if peer dependency is mismatched.

**Comment by Js-Brecht** [comment]
Hey @arafatamim, thanks for letting me know.  I will go ahead and update the `peerDependency` for Gatsby to allow v4

Question: does Netlify support pnpm natively now, perhaps with `strict-peer-dependencies` turned on?  I've had my own Netlify plugin for the longest time just so I can use `pnpm` in deployments.

**Comment by Js-Brecht** [comment]
Published in `gatsby-plugin-pnpm@1.2.9`

**Comment by arafatamim** [comment]
Netlify still doesn't support pnpm. I personally have been using the built-in npm to install deps on the Netlify side of things.
