### ISSUE TITLE
[gatsby-plugin-pnpm] You must have Gatsby installed to use this plugin!

### ISSUE THREAD

**Issue by nurhakam** [Js-Brecht/gatsby-plugin-pnpm#12]
EDIT: Installed wrong plugin. I thought it was for yarn Plug n Play webpack problem.

I'm encountered this issue and can't find a way to resolve it.

`> Executing task: yarn run develop <

verbose set gatsby_log_level: "verbose"
verbose set gatsby_executing_command: "develop"
verbose loading local command from:
C:\...\.yarn\unplugged\gatsby-virtual-b3e9cb92f4\node_modules\gatsby\dist\commands\develop.js
verbose running command: develop

verbose Transition to "initializing"
success compile gatsby files - 1.721s
success load gatsby config - 0.156s
success load plugins - 4.387s
success onPreInit - 0.019s
success initialize cache - 0.229s
success copy gatsby files - 0.712s
verbose Attaching functions to development server
success Compiling Gatsby Functions - 0.938s
success onPreBootstrap - 1.051s
verbose Creating 1 worker
verbose Transition to "initializingData"
success createSchemaCustomization - 0.026s
verbose Transition to "initializingData" > "sourcingNodes"
verbose Checking for deleted pages
verbose Deleted 0 pages
verbose Found 0 changed pages
success Checking for changed pages - 0.018s
success source and transform nodes - 4.109s
verbose Transition to "initializingData" > "buildingSchema"
success building schema - 1.477s
verbose Transition to "initializingData" > "creatingPages"
success createPages - 0.211s
success createPagesStatefully - 0.367s
info Total nodes: 122, SitePage nodes: 23 (use --verbose for breakdown)
verbose Number of node types: 8. Nodes per type: Directory: 5, File: 22, ImageSharp: 11, Mdx: 10, Site: 1, SiteBuildMetadata: 1, SitePage:
23, SitePlugin: 49
verbose Checking for deleted pages
verbose Deleted 0 pages
verbose Found 23 changed pages
success Checking for changed pages - 0.013s
verbose Transition to "initializingData" > "writingOutRedirects"
success write out redirect data - 0.013s
verbose Transition to "initializingData" > "done"
verbose Transition to "runningPostBootstrap"
success Build manifest and related icons - 0.295s
success onPostBootstrap - 0.362s
info bootstrap finished - 25.318s
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.017s
success extract queries from components - 7.356s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.063s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"
success run page queries - 1.011s - 3/3 2.97/s
verbose Transition to "runningQueries" > "waitingForJobs"
success Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 11.648s - 6/6 0.52/s
verbose Transition to "runningQueries" > "done"
verbose Transition to "startingDevServers"

 ERROR 

[gatsby-plugin-pnpm] You must have Gatsby installed to use this plugin!

not finished Building development bundle - 0.138s

The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn run develop" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.`

**Comment by lxfu1** [comment]
I have the same question!

**Comment by lxfu1** [comment]
So, how to resolve it? could you reopen it!

**Comment by Js-Brecht** [comment]
@lxfu1 Please open a new issue, with actual details about the issue.  If you hadn't noticed, the OP stated that it had been installed (mistakenly) for use with Yarn 3 PnP, which this plugin is definitely not for.  In order to help you, more information is needed than just an error, and the best place for that is going to be a new issue.
